# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  api_key: 5049823
  api_secret: cYk6lG1tDsXtBhhdrkh0

development:
  secret_key_base: db9fe915b536694c669ee8533baa0707d32af731c613835ebebfc3a2a965d51a0ed7a2132886b342b741351f8bf7133f225fcfae72a3b26d99884be7d50f2da4
  <<: *default

test:
  secret_key_base: e59342e8c64bda01aeb6a4a8ffe836f7ceaaf9f8d38ed90c972b3161d80a3a3033aedc098ed97aa5f14dd0b1f116bf65eaaeaedfe8a522d7bd84342d130a03c0
  <<: *default
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
<<: *default